on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build and test (desktop platforms)
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            build_command: flutter build linux --release
            test_command: flutter run test/native_test.dart
            artifact_dir: build/linux

          - os: macos-latest
            build_command: flutter build macos --release
            test_command: flutter run test/native_test.dart
            artifact_dir: build/macos

          - os: windows-latest
            build_command: flutter build windows --release
            test_command: flutter run test/native_test.dart
            artifact_dir: build/windows/runner/Release

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable

      # Ninja is required for using CMake (building on Windows/Linux)
      - uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.11.1

      - run: flutter doctor -v

      - run: flutter pub get
        working-directory: ${{ github.workspace }}

      - run: flutter pub get
        working-directory: ${{ github.workspace }}/example

      - run: flutter pub get
        working-directory: ${{ github.workspace }}/cargokit/build_tool

      - run: flutter analyze

      - run: ${{ matrix.build_command }}
        working-directory: ${{ github.workspace }}/example

      - run: ${{ matrix.test_command }}
        working-directory: ${{ github.workspace }}/example

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/example/${{ matrix.artifact_dir }}
