on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build and test (desktop platforms)
jobs:
  build:
    # See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-13, windows-latest ]
        include:
          - os: ubuntu-latest
            build_command: flutter build linux --release --obfuscate --split-debug-info=symbols --verbose
            test_command: xvfb-run flutter test integration_test
            artifact_dir: build/linux

          - os: macos-13
            build_command: flutter build macos --release --obfuscate --split-debug-info=symbols --verbose
            test_command: flutter test integration_test
            artifact_dir: build/macos/Build/Products/Release

          - os: windows-latest
            build_command: flutter build windows --release --obfuscate --split-debug-info=symbols --verbose
            test_command: flutter test integration_test
            artifact_dir: build/windows/runner/Release

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable

      # Ninja and GTK are required for building on Linux
      - if: (matrix.os == 'ubuntu-latest')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev

      - run: flutter doctor -v

      - run: |
          flutter pub get
          flutter pub get -C example
          flutter pub get -C cargokit/build_tool

      - run: flutter analyze

      - run: ${{ matrix.build_command }}
        working-directory: ${{ github.workspace }}/example

      - run: ${{ matrix.test_command }}
        working-directory: ${{ github.workspace }}/example

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/example/symbols
            ${{ github.workspace }}/example/${{ matrix.artifact_dir }}
