on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Integration test (iOS)
jobs:
  build:
    # See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      matrix:
        model: [ 'iPhone 14' ]

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      # - name: Flutter build
      #   run: cd example && flutter build ipa --release --obfuscate --split-debug-info=symbols --no-codesign

      # See: https://github.com/flutter/flutter/issues/105913
      - name: Pre-build for integration test
        run: cd example && flutter build ios --debug --simulator

      # See: https://github.com/marketplace/actions/launch-ios-simulator
      - name: Launch iOS simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ matrix.model }}

      - name: Flutter integration test
        run: cd example && flutter test integration_test

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts-ios
      #     path: |
      #       ${{ github.workspace }}/example/symbols
      #       ${{ github.workspace }}/example/build/ios
