on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build and test (iOS)
jobs:
  build:
    # See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      matrix:
        model: [ "iPhone 11" ]

    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: |
          flutter pub get
          flutter pub get -C example
          flutter pub get -C cargokit/build_tool

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter build
        run: cd example && flutter build ios --release --obfuscate --split-debug-info=symbols

      - name: Launch iOS simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ matrix.model }}

      - name: Flutter integration test
        run: cd example && flutter test integration_test

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-android
          path: |
            ${{ github.workspace }}/example/symbols
            ${{ github.workspace }}/example/build
